### PR TITLE
Add SSL server cipher/protocol/session cache/oscp stapling configuration

### PR DESCRIPTION
**Pull request by andytson-inviqa**

### CODE REVIEW

**Comment by andytson-inviqa** [comment]
I've tested and fixed some issues in this, seems ok now

**Comment by andytson-inviqa** [comment]
actually, a Nginx error

**Comment by andytson-inviqa** [comment]
fixed

**Comment by sroze** [comment]
I've no idea what this is about. So @kierenevans I let you have a look 😄

**Pull request merged**
