### PR TITLE
Add support for postgres assets database import

### PR DESCRIPTION
**Pull request by andytson-inviqa**

### CODE REVIEW

**Comment by andytson-inviqa** [comment]
I'm not really sure about what to do with installing the postgres cli/php extension. Installing both the mysql and postgres tools in the same image is wasteful, yet having separate images is too messy

**Comment by andytson-inviqa** [comment]
I suppose this is a good reason to separate the assets code from the PHP image

**Comment by sroze** [comment]
> Installing both the mysql and postgres tools in the same image is wasteful

I wouldn't say so, it's not that bad, and very convenient for users :)

**Comment by andytson-inviqa** [comment]
yep, convenient for users, but not for servers :) I'll make it install both (and that'll fix the docker lint checks)

**Comment by andytson-inviqa** [comment]
I've tested and it works against the project I was using this for

**Pull request merged**
