### PR TITLE
Remove settings file completely from drupal8.

### PR DESCRIPTION
**Pull request by kierenevans**

### CODE REVIEW

**Comment by sroze** [comment]
So does this configuration file needs to be created in all projects?

**Comment by tonypiper** [comment]
@Chapabu any thoughts on this?

**Comment by Chapabu** [comment]
There will need to be a config file of some sort on the project, but this is fairly normal for Drupal hosting (i.e Acquia needs specific settings, Platform.sh needs specific settings, etc).

So long as it's documented, it should be fine.

I'll be backporting settings from a working project into https://github.com/continuouspipe/drupal8-lightning at some point this week.

**Comment by sroze** [comment]
Thanks @Chapabu. I've created the issue continuouspipe/drupal8-lightning#24 for you :)

**Pull request merged**
