### PR TITLE
Add a cron supervisor service that starts if START_MODE=cron

### PR DESCRIPTION
**Pull request by andytson-inviqa**

### CODE REVIEW

**Comment by andytson-inviqa** [comment]
I wish there was a decent cron we can trust that allowed logging everything to stdout/err

**Comment by sroze** [comment]
Why not moving this cron directly to the ubuntu image?

**Comment by andytson-inviqa** [comment]
@sroze I'm happy to move it there if others are

**Comment by sroze** [comment]
@kierenevans what do you think?

**Comment by kierenevans** [comment]
Images without web servers or php will probably still need the ability to run a scheduled task somehow.
I am wary of moving it up to our ubuntu image in terms of adding clutter, but on the other hand we shouldn't need to solve something more than once.

**Comment by andytson-inviqa** [comment]
how about a intermediate layer?

**Comment by andytson-inviqa** [comment]
I've moved it to the Ubuntu image now. It's not much clutter as it's just the supervisor config, and cron is already installed in the ubuntu Dockerfile

**Pull request merged**
