### PR TITLE
Do not overwrite the `START_CRON` variable if already exists

### PR DESCRIPTION
**Pull request by sroze**

### CODE REVIEW

**Comment by sroze** [comment]
I have to say... this still says this on Heroku:
```
$ cron -f
seteuid: Operation not permitted
```

**Comment by andytson-inviqa** [comment]
https://devcenter.heroku.com/articles/scheduler

**Comment by sroze** [comment]
@andytson-inviqa that's a quite succinct answer 😄 We have cronjobs to run every minute, so I don't think we should use the scheduler that (as far as I understood) is starting new dynos each time.

**Comment by andytson-inviqa** [comment]
it goes on to mention clock processes and message workers https://devcenter.heroku.com/articles/scheduled-jobs-custom-clock-processes

**Comment by andytson-inviqa** [comment]
though technically cronie is a clock process

**Pull request merged**
