### PR TITLE
Spryker: A failed frontend build should still fail the build

### PR DESCRIPTION
**Pull request by kierenevans**
Reverses the exit code ignoring change from https://github.com/continuouspipe/dockerfiles/commit/efac7db83edd722396c4838580470ca4bc00e18f

### CODE REVIEW

**Comment by andytson-inviqa** [comment]
Why the original exit code ignoring change in the first place @kierenevans ?

**Comment by andytson-inviqa** [comment]
and how does a frontend build fail if it's silently ignoring failures?

**Comment by kierenevans** [comment]
I'm not entirely sure - I guess it was to let it build when we were testing it to get past the frontend build and onto "does the image work", but we shouldn't be ignoring errors anyway!

**Comment by sroze** [comment]
Andy, happy with this one as well?

**Pull request merged**
