### PR TITLE
Add Mailcatcher image build

### PR DESCRIPTION
**Pull request by andytson-inviqa**

### CODE REVIEW

**Comment by sroze** [comment]
The linter said that you need to precise a maintainer :)

> Specify a maintainer of the Dockerfile

**Comment by andytson-inviqa** [comment]
sorted, ready for review (I changed it also to run from supervisord and use standard SMTP/HTTP ports)

**Comment by tonypiper** [comment]
Just a question - do we need to protect this from drive-by port-scanners?

**Comment by kierenevans** [comment]
For CP, I would recommend not exposing the ports to the world. If on a trusted kubenetes cluster, it should be alright.
Outside CP, yes we would need some sort of protection.

**Comment by andytson-inviqa** [comment]
@tonypiper I was thinking for another PR to have an Nginx without PHP layer that could be used to protect if actually exposed (well unless httplabs will be done and done as a container for the only exposed ports of a project)

**Pull request merged**
