### PR TITLE
Added Yarn to Drupal images

### PR DESCRIPTION
**Pull request by Chapabu**
We've added Yarn to almost every project so far, so it makes sense to have it in the base image.

### CODE REVIEW

**Comment by andytson-inviqa** [comment]
should we switch all base image calls to `npm` to `yarn` as well?

**Comment by kierenevans** [comment]
There doesn't appear to be any frontend setup for the drupal image currently but it would be nice for the other images.

**Comment by andytson-inviqa** [comment]
yarn doesn't appear to port over npm shrinkwrap files, so forcing migration might cause issues where dependencies are loose

**Comment by andytson-inviqa** [comment]
This PR doesn't force in any case for drupal

**Comment by Chapabu** [comment]
You can still use `npm` if `yarn` is installed, so that should be fine.

**Pull request merged**
