### PR TITLE
Add detection and support for Symfony Flex structure

### PR DESCRIPTION
**Pull request by andytson-inviqa**
depends on #396 and #374 to work

### CODE REVIEW

**Comment by andytson-inviqa** [comment]
I've tested this against symfony/skeleton and symfony/framework-standard-edition and they appear to be getting the right environment variables

**Comment by TerjeBr** [comment]
This PR has broken our build!

/usr/local/share/40-stack has this line:
`export APP_ENDPOINT=${APP_ENDPOINT:-/index.php}`

Before DEFAULT_APP_ENDPOINT was computed and used to set APP_ENDPOINT to `/app.php`
in /usr/local/share/env/30-framework
This logic with DEFAULT_APP_ENDPOINT has been moved to /usr/local/share/env/45-framework, but that runs after /usr/local/share/40-stack, so the APP_ENDPOINT now always ends up as /index.php.

**Comment by andytson** [comment]
@TerjeBr sorry to hear that. You can use the :stable tag, which doesn't have this in.

The :stable tag is what we recommend using by default, but the :latest has at least identified this as an issue for you ahead of us tagging :latest as :stable

**Comment by andytson** [comment]
we will probably fix by moving the APP_ENDPOINT in /usr/local/share/40-stack later to avoid the issue

**Pull request merged**
