### PR TITLE
Reduce all Dockerfile COPY's to a single layer

### PR DESCRIPTION
**Pull request by andytson-inviqa**
This excludes the php images, which are done in another PR

### CODE REVIEW

**Comment by sroze** [comment]
What the value of that?

**Comment by andytson-inviqa** [comment]
I don't think layers are as bad as they used to, but less layers in COPY would have some performance boost somewhere

**Comment by sroze** [comment]
I definitely love the other PR but I'm afraid this one is too much of an optimisation that reduces a lot the clarity of these dockerfiles. I personally vote for keeping them as they are, with two `COPY`, just for the sake of better user experience.

**Comment by andytson-inviqa** [comment]
I'm happy to drop this if that's an issue, but what clarity is lost?

**Comment by sroze** [comment]
From a user perspective, this is more or less obvious:
```Dockerfile
COPY ./etc/ /etc
COPY ./usr/ /usr
```

This one is much less:
```Dockerfile
COPY ./shared/ /
```

And these Dockerfiles are also a source of inspiration for the people that are using them, therefore I suggest we keep it very simple.

**Comment by andytson-inviqa** [comment]
the latter style is already being used in some images with nginx/apache varients

**Comment by andytson-inviqa** [comment]
but I disagree that / is less clear than /folder

**Pull request closed without merging**
