### PR TITLE
Allow args to passthru to tasks

### PR DESCRIPTION
**Pull request by dcole-inviqa**
can we allow args to be preserved and passed through to the task being called.

### CODE REVIEW

**Comment by andytson-inviqa** [comment]
I was thinking of doing this also, but wasn't decided on whether to instead allow multiple do_ functions to be specified instead of function arguments

**Comment by dcole-inviqa** [comment]
fixed the shellcheck issues if you decide to go with with this approach, feel free to close if you go with the other approach :)

**Comment by dcole-inviqa** [comment]
as a compromise i guess you could have a core task which runs multiple....

do_chain() { 
 for (task in $@)
 do
   "do_$task"
 done
}

**Comment by andytson-inviqa** [comment]
yep, sounds good

**Pull request merged**
