### PR TITLE
Give /usr/local/share/env/ files access to baseimage functions

### PR DESCRIPTION
**Pull request by andytson-inviqa**
by changing the order of load

### CODE REVIEW

**Comment by andytson-inviqa** [comment]
appears to have a bug caused by it not having cd /app 'd yet:
jq: error: Could not open file composer.lock: No such file or directory
/usr/local/share/env/45-framework: line 3: [: : integer expression expected

**Comment by andytson-inviqa** [comment]
actually, more an issue with the other PR with a chicken and egg scenario

**Comment by sroze** [comment]
@andytson-inviqa would this be resolved by adding a `WORKDIR /app` in the PHP base image?

**Comment by andytson** [comment]
no, it's resolved now

**Comment by sroze** [comment]
Great. Then if @kierenevans is happy, I guess you can merge :)

**Pull request merged**
